badges = [
    {
        'Position': 'POINT GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Dimer (HoF)',
        'Badge2': 'Ankle Breaker (HoF)',
        'Badge3': 'Pick & Roll Maestro (HoF)',
        'Badge4': 'Lob City Passer (HoF)',
        'Badge5': 'Flashy Passer (HoF)',
        'Ameythst': 5,
        'Gold': 5,
        'Silver': 3,
        'Bronze': 6,
        'Total': 19,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Shot Creating',
        'Badge1': 'Ankle Breaker (HoF)',
        'Badge2': 'Dimer (Gold)',
        'Badge3': 'Pick & Roll Maestro (Gold)',
        'Badge4': 'Lob City Passer (Gold)',
        'Badge5': 'Flashy Passer (Gold)',
        'Ameythst': 1,
        'Gold': 10,
        'Silver': 4,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Dimer (Gold)',
        'Badge2': 'Pick & Roll Maestro (Gold)',
        'Badge3': 'Flashy Passer (Gold)',
        'Badge4': 'Lob City Passer (Gold)',
        'Badge5': 'Ankle Breaker (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 9,
        'Bronze': 5,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Ankle Breaker (HoF)',
        'Badge2': 'Dimer (Gold)',
        'Badge3': 'Pick & Roll Maestro (Gold)',
        'Badge4': 'Lob City Passer (Gold)',
        'Badge5': 'Flashy Passer (Gold)',
        'Ameythst': 1,
        'Gold': 9,
        'Silver': 5,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Defending',
        'Badge1': 'Dimer (Gold)',
        'Badge2': 'Lob City Passer (Gold)',
        'Badge3': 'Ankle Breaker (Gold)',
        'Badge4': 'Pick & Roll Maestro (Gold)',
        'Badge5': 'Flashy Passer (Gold)',
        'Ameythst': 0,
        'Gold': 9,
        'Silver': 6,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Rebounding',
        'Badge1': 'Dimer (Gold)',
        'Badge2': 'Break Starter (Gold)',
        'Badge3': 'Lob City Passer (Gold)',
        'Badge4': 'Ankle Breaker (Gold)',
        'Badge5': 'Pick & Roll Maestro (Gold)',
        'Ameythst': 0,
        'Gold': 10,
        'Silver': 3,
        'Bronze': 9,
        'Total': 22,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'PostScoring',
        'Badge1': 'Dimer (Gold)',
        'Badge2': 'Pick & Roll Maestro (Gold)',
        'Badge3': 'Lob City Passer (Gold)',
        'Badge4': 'Flashy Passer (Gold)',
        'Badge5': 'Ankle Breaker (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 10,
        'Bronze': 4,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Ankle Breaker (HoF)',
        'Badge2': 'Tireless Scorer (HoF)',
        'Badge3': 'Difficult Shots (HoF)',
        'Badge4': 'Mid Range Deadeye (Gold)',
        'Badge5': 'Tear Dropper (Gold)',
        'Ameythst': 3,
        'Gold': 5,
        'Silver': 7,
        'Bronze': 6,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Shot Creating',
        'Badge1': 'Mid Range Deadeye (HoF)',
        'Badge2': 'Tear Dropper (HoF)',
        'Badge3': 'Tireless Scorer (HoF)',
        'Badge4': 'Difficult Shots (HoF)',
        'Badge5': 'Ankle Breaker (Gold)',
        'Ameythst': 4,
        'Gold': 4,
        'Silver': 4,
        'Bronze': 8,
        'Total': 20,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Shot Creating',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Tireless Scorer (HoF)',
        'Badge2': 'Difficult Shots (HoF)',
        'Badge3': 'Mid Range Deadeye (HoF)',
        'Badge4': 'Tear Dropper (Gold)',
        'Badge5': 'Ankle Breaker (Gold)',
        'Ameythst': 3,
        'Gold': 5,
        'Silver': 6,
        'Bronze': 10,
        'Total': 24,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Tear Dropper (HoF)',
        'Badge2': 'Tireless Scorer (Gold)',
        'Badge3': 'Mid Range Deadeye (Gold)',
        'Badge4': 'Difficult Shots (Gold)',
        'Badge5': 'Ankle Breaker (Gold)',
        'Ameythst': 1,
        'Gold': 10,
        'Silver': 1,
        'Bronze': 11,
        'Total': 23,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Defending',
        'Badge1': 'Mid Range Deadeye (Gold)',
        'Badge2': 'Tear Dropper (Gold)',
        'Badge3': 'Tireless Scorer (Gold)',
        'Badge4': 'Difficult Shots (Gold)',
        'Badge5': 'Ankle Breaker (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 10,
        'Total': 25,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Rebounding',
        'Badge1': 'Tear Dropper (Gold)',
        'Badge2': 'Mid Range Deadeye (Gold)',
        'Badge3': 'Tireless Scorer (Gold)',
        'Badge4': 'Difficult Shots (Gold)',
        'Badge5': 'Ankle Breaker (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 6,
        'Bronze': 12,
        'Total': 26,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'PostScoring',
        'Badge1': 'Tear Dropper (HoF)',
        'Badge2': 'Tireless Scorer (Gold)',
        'Badge3': 'Difficult Shots (Gold)',
        'Badge4': 'Mid Range Deadeye (Gold)',
        'Badge5': 'Up & Under Specialist (Gold)',
        'Ameythst': 1,
        'Gold': 9,
        'Silver': 4,
        'Bronze': 8,
        'Total': 22,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Corner Specialist (Gold)',
        'Badge2': 'Catch & Shoot (Gold)',
        'Badge3': 'Deep Range Deadeye (Gold)',
        'Badge4': 'Limitless Range (Gold)',
        'Badge5': 'Tireless Scorer (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 8,
        'Bronze': 5,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Shot Creating',
        'Badge1': 'Corner Specialist (Gold)',
        'Badge2': 'Tireless Scorer (Gold)',
        'Badge3': 'Catch & Shoot (Gold)',
        'Badge4': 'Deep Range Deadeye (Gold)',
        'Badge5': 'Limitless Range (Gold)',
        'Ameythst': 0,
        'Gold': 10,
        'Silver': 2,
        'Bronze': 10,
        'Total': 22,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Catch & Shoot (HoF)',
        'Badge2': 'Deep Range Deadeye (HoF)',
        'Badge3': 'Limitless Range (HoF)',
        'Badge4': 'Corner Specialist (HoF)',
        'Badge5': 'Tireless Scorer (Gold)',
        'Ameythst': 4,
        'Gold': 4,
        'Silver': 3,
        'Bronze': 6,
        'Total': 17,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Tireless Scorer (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 9,
        'Bronze': 8,
        'Total': 24,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Defending',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Tireless Scorer (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 8,
        'Bronze': 10,
        'Total': 25,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Rebounding',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Tireless Scorer (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 10,
        'Total': 24,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'PostScoring',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Tireless Scorer (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 9,
        'Bronze': 7,
        'Total': 23,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'One Man Fast Break (HoF)',
        'Badge2': 'Acrobat (HoF)',
        'Badge3': 'Relentless Finisher (Gold)',
        'Badge4': 'Posterizer (Gold)',
        'Badge5': 'Ankle Breaker (Gold)',
        'Ameythst': 2,
        'Gold': 6,
        'Silver': 6,
        'Bronze': 7,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Shot Creating',
        'Badge1': 'Acrobat (HoF)',
        'Badge2': 'Relentless Finisher (HoF)',
        'Badge3': 'One Man Fastbreak (HoF)',
        'Badge4': 'Tear Dropper (Gold)',
        'Badge5': 'Posterizer (Gold)',
        'Ameythst': 3,
        'Gold': 6,
        'Silver': 3,
        'Bronze': 11,
        'Total': 23,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Posterizer (Gold)',
        'Badge2': 'Relentless Finisher (Gold)',
        'Badge3': 'Acrobat (Gold)',
        'Badge4': 'One Man Fast Break (Gold)',
        'Badge5': 'Tear Dropper (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 6,
        'Bronze': 12,
        'Total': 26,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Posterizer (HoF)',
        'Badge2': 'Relentless Finisher (HoF)',
        'Badge3': 'Acrobat (HoF)',
        'Badge4': 'One Man Fastbreak (HoF)',
        'Badge5': 'Tear Dropper (Gold)',
        'Ameythst': 4,
        'Gold': 4,
        'Silver': 3,
        'Bronze': 11,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Defending',
        'Badge1': 'Posterizer (HoF)',
        'Badge2': 'Acrobat (HoF)',
        'Badge3': 'One Man Fast Break (HoF)',
        'Badge4': 'Relentless Finisher (Gold)',
        'Badge5': 'Tear Dropper (Silver)',
        'Ameythst': 3,
        'Gold': 4,
        'Silver': 9,
        'Bronze': 6,
        'Total': 22,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Rebounding',
        'Badge1': 'Posterizer (HoF)',
        'Badge2': 'One Man Fast Break (HoF)',
        'Badge3': 'Relentless Finisher (Gold)',
        'Badge4': 'Acrobat (Gold)',
        'Badge5': 'Tear Dropper (Gold)',
        'Ameythst': 2,
        'Gold': 6,
        'Silver': 6,
        'Bronze': 9,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'PostScoring',
        'Badge1': 'Relentless Finisher (HoF)',
        'Badge2': 'Acrobat (HoF)',
        'Badge3': 'Posterizer (Gold)',
        'Badge4': 'One Man Fast Break (Gold)',
        'Badge5': 'Tear Dropper (Gold)',
        'Ameythst': 2,
        'Gold': 6,
        'Silver': 5,
        'Bronze': 10,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Defending',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Charge Card (Gold)',
        'Badge3': 'Pick Pocket (Gold)',
        'Badge4': 'Pick Dodger (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 9,
        'Bronze': 4,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Defending',
        'Secondary': 'Shot Creating',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Charge Card (Gold)',
        'Badge3': 'Pick Pocket (Gold)',
        'Badge4': 'Pick Dodger (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 8,
        'Bronze': 5,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Defending',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Charge Card (Gold)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Pick Pocket (Gold)',
        'Badge4': 'Pick Dodger (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 6,
        'Bronze': 9,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Defending',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Pick Pocket (Gold)',
        'Badge3': 'Pick Dodger (Gold)',
        'Badge4': 'Charge Card (Gold)',
        'Badge5': 'Posterizer (Gold)',
        'Ameythst': 0,
        'Gold': 11,
        'Silver': 3,
        'Bronze': 5,
        'Total': 19,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Defending',
        'Secondary': 'Defending',
        'Badge1': 'Defensive Stopper (HoF)',
        'Badge2': 'Pick Pocket (HoF)',
        'Badge3': 'Pick Dodger (HoF)',
        'Badge4': 'Charge Card (HoF)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 4,
        'Gold': 4,
        'Silver': 4,
        'Bronze': 5,
        'Total': 17,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Defending',
        'Secondary': 'Rebounding',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Pick Dodger (Gold)',
        'Badge4': 'Charge Card (Gold)',
        'Badge5': 'Pick Pocket (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 6,
        'Bronze': 5,
        'Total': 19,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POINT GUARD',
        'Primary': 'Defending',
        'Secondary': 'PostScoring',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Charge Card (Gold)',
        'Badge4': 'Pick Pocket (Gold)',
        'Badge5': 'Pick Dodger (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 6,
        'Bronze': 7,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Dimer (HoF)',
        'Badge2': 'Ankle Breaker (HoF)',
        'Badge3': 'Pick & Roll Maestro (HoF)',
        'Badge4': 'Lob City Passer (HoF)',
        'Badge5': 'Flashy Passer (HoF)',
        'Ameythst': 5,
        'Gold': 5,
        'Silver': 3,
        'Bronze': 6,
        'Total': 19,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Shot Creating',
        'Badge1': 'Ankle Breaker (HoF)',
        'Badge2': 'Dimer (Gold)',
        'Badge3': 'Lob City Passer (Gold)',
        'Badge4': 'Flashy Passer (Gold)',
        'Badge5': 'Pick & Roll Maestro (Gold)',
        'Ameythst': 1,
        'Gold': 10,
        'Silver': 4,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Lob City Passer (Gold)',
        'Badge2': 'Flashy Passer (Gold)',
        'Badge3': 'Dimer (Gold)',
        'Badge4': 'Ankle Breaker (Gold)',
        'Badge5': 'Pick & Roll Maestro (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 9,
        'Bronze': 5,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Ankle Breaker (HoF)',
        'Badge2': 'Dimer (Gold)',
        'Badge3': 'Lob City Passer (Gold)',
        'Badge4': 'Flashy Passer (Gold)',
        'Badge5': 'One Man Fast Break (Gold)',
        'Ameythst': 1,
        'Gold': 9,
        'Silver': 5,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Defending',
        'Badge1': 'Dimer (Gold)',
        'Badge2': 'Ankle Breaker (Gold)',
        'Badge3': 'Pick & Roll Maestro (Gold)',
        'Badge4': 'Lob City Finisher (Gold)',
        'Badge5': 'Flashy Passer (Gold)',
        'Ameythst': 0,
        'Gold': 9,
        'Silver': 6,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Rebounding',
        'Badge1': 'Break Starter (Gold)',
        'Badge2': 'Lob City Passer (Gold)',
        'Badge3': 'Dimer (Gold)',
        'Badge4': 'Ankle Breaker (Gold)',
        'Badge5': 'Pick & Roll Maestro (Gold)',
        'Ameythst': 0,
        'Gold': 10,
        'Silver': 3,
        'Bronze': 10,
        'Total': 23,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'PostScoring',
        'Badge1': 'Lob City Passer (Gold)',
        'Badge2': 'Flashy Passer (Gold)',
        'Badge3': 'Dimer (Gold)',
        'Badge4': 'Ankle Breaker (Gold)',
        'Badge5': 'Pick & Roll Maestro (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 10,
        'Bronze': 4,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Tireless Scorer (HoF)',
        'Badge2': 'Difficult Shots (HoF)',
        'Badge3': 'Ankle Breaker (Gold)',
        'Badge4': 'Mid Range Deadeye (Gold)',
        'Badge5': 'Tear Dropper (Gold)',
        'Ameythst': 2,
        'Gold': 6,
        'Silver': 7,
        'Bronze': 6,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Shot Creating',
        'Badge1': 'Mid Range Deadeye (HoF)',
        'Badge2': 'Tear Dropper (HoF)',
        'Badge3': 'Tireless Scorer (HoF)',
        'Badge4': 'Difficult Shots (HoF)',
        'Badge5': 'Ankle Breaker (Gold)',
        'Ameythst': 4,
        'Gold': 4,
        'Silver': 4,
        'Bronze': 8,
        'Total': 20,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Shot Creating',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Tireless Scorer (HoF)',
        'Badge2': 'Difficult Shots (HoF)',
        'Badge3': 'Mid Range Deadeye (HoF)',
        'Badge4': 'Tear Dropper (Gold)',
        'Badge5': 'Corner Specialist (Silver)',
        'Ameythst': 3,
        'Gold': 4,
        'Silver': 7,
        'Bronze': 9,
        'Total': 23,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Tear Dropper (HoF)',
        'Badge2': 'Tireless Scorer (Gold)',
        'Badge3': 'Mid Range Deadeye (Gold)',
        'Badge4': 'Difficult Shots (Gold)',
        'Badge5': 'Relentless Finisher (Gold)',
        'Ameythst': 1,
        'Gold': 10,
        'Silver': 1,
        'Bronze': 10,
        'Total': 22,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Defending',
        'Badge1': 'Mid Range Deadeye (Gold)',
        'Badge2': 'Tear Dropper (Gold)',
        'Badge3': 'Tireless Scorer (Gold)',
        'Badge4': 'Difficult Shots (Gold)',
        'Badge5': 'Ankle Breaker (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 8,
        'Bronze': 7,
        'Total': 22,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Rebounding',
        'Badge1': 'Tear Dropper (Gold)',
        'Badge2': 'Mid Range Deadeye (Gold)',
        'Badge3': 'Tireless Scorer (Gold)',
        'Badge4': 'Difficult Shots (Gold)',
        'Badge5': 'Ankle Breaker (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 11,
        'Total': 25,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Shot Creating',
        'Secondary': 'PostScoring',
        'Badge1': 'Tear Dropper (HoF)',
        'Badge2': 'Tireless Scorer (Gold)',
        'Badge3': 'Difficult Shots (Gold)',
        'Badge4': 'Mid Range Deadeye (Gold)',
        'Badge5': 'Up & Under Specialist (Gold)',
        'Ameythst': 1,
        'Gold': 8,
        'Silver': 5,
        'Bronze': 7,
        'Total': 21,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Corner Specialist (Gold)',
        'Badge2': 'Catch & Shoot (Gold)',
        'Badge3': 'Deep Range Deadeye (Gold)',
        'Badge4': 'Limitless Range (Gold)',
        'Badge5': 'Tireless Scorer (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 8,
        'Bronze': 5,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Shot Creating',
        'Badge1': 'Corner Specialist (Gold)',
        'Badge2': 'Tireless Scorer (Gold)',
        'Badge3': 'Catch & Shoot (Gold)',
        'Badge4': 'Deep Range Deadeye (Gold)',
        'Badge5': 'Limitless Range (Gold)',
        'Ameythst': 0,
        'Gold': 10,
        'Silver': 2,
        'Bronze': 8,
        'Total': 20,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Catch & Shoot (HoF)',
        'Badge2': 'Deep Range Deadeye (HoF)',
        'Badge3': 'Limitless Range (HoF)',
        'Badge4': 'Corner Specialist (HoF)',
        'Badge5': 'Tireless Scorer (Gold)',
        'Ameythst': 4,
        'Gold': 4,
        'Silver': 3,
        'Bronze': 4,
        'Total': 15,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Tireless Scorer (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 9,
        'Bronze': 6,
        'Total': 22,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Defending',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Tireless Scorer (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 8,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Rebounding',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Tireless Scorer (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 8,
        'Total': 22,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'PostScoring',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Tireless Scorer (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 9,
        'Bronze': 5,
        'Total': 21,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'One Man Fast Break (HoF)',
        'Badge2': 'Acrobat (HoF)',
        'Badge3': 'Relentless Finisher (Gold)',
        'Badge4': 'Posterizer (Gold)',
        'Badge5': 'Ankle Breaker (Gold)',
        'Ameythst': 2,
        'Gold': 6,
        'Silver': 8,
        'Bronze': 5,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Shot Creating',
        'Badge1': 'Relentless Finisher (HoF)',
        'Badge2': 'Acrobat (HoF)',
        'Badge3': 'One Man Fastbreak (HoF)',
        'Badge4': 'Tear Dropper (Gold)',
        'Badge5': 'Posterizer (Gold)',
        'Ameythst': 3,
        'Gold': 5,
        'Silver': 6,
        'Bronze': 8,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Posterizer (Gold)',
        'Badge2': 'Relentless Finisher (Gold)',
        'Badge3': 'Acrobat (Gold)',
        'Badge4': 'One Man Fast Break (Gold)',
        'Badge5': 'Tear Dropper (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 10,
        'Total': 25,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Posterizer (HoF)',
        'Badge2': 'Relentless Finisher (HoF)',
        'Badge3': 'Acrobat (HoF)',
        'Badge4': 'One Man Fastbreak (HoF)',
        'Badge5': 'Tear Dropper (Gold)',
        'Ameythst': 4,
        'Gold': 4,
        'Silver': 3,
        'Bronze': 11,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Defending',
        'Badge1': 'Posterizer (HoF)',
        'Badge2': 'One Man Fast Break (HoF)',
        'Badge3': 'Acrobat (Gold)',
        'Badge4': 'Relentless Finisher (Gold)',
        'Badge5': 'Tear Dropper (Silver)',
        'Ameythst': 2,
        'Gold': 5,
        'Silver': 8,
        'Bronze': 4,
        'Total': 19,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Rebounding',
        'Badge1': 'Posterizer (HoF)',
        'Badge2': 'One Man Fast Break (HoF)',
        'Badge3': 'Relentless Finisher (Gold)',
        'Badge4': 'Acrobat (Gold)',
        'Badge5': 'Tear Dropper (Gold)',
        'Ameythst': 2,
        'Gold': 5,
        'Silver': 6,
        'Bronze': 10,
        'Total': 23,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'PostScoring',
        'Badge1': 'Relentless Finisher (HoF)',
        'Badge2': 'Acrobat (HoF)',
        'Badge3': 'Posterizer (Gold)',
        'Badge4': 'One Man Fast Break (Gold)',
        'Badge5': 'Tear Dropper (Gold)',
        'Ameythst': 2,
        'Gold': 6,
        'Silver': 6,
        'Bronze': 9,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Defending',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Charge Card (Gold)',
        'Badge3': 'Pick Pocket (Gold)',
        'Badge4': 'Pick Dodger (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 9,
        'Bronze': 5,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Defending',
        'Secondary': 'Shot Creating',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Charge Card (Gold)',
        'Badge3': 'Pick Pocket (Gold)',
        'Badge4': 'Pick Dodger (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 8,
        'Bronze': 5,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Defending',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Charge Card (Gold)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Pick Pocket (Gold)',
        'Badge4': 'Pick Dodger (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 6,
        'Bronze': 8,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Defending',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Pick Pocket (Gold)',
        'Badge3': 'Pick Dodger (Gold)',
        'Badge4': 'Charge Card (Gold)',
        'Badge5': 'Posterizer (Gold)',
        'Ameythst': 0,
        'Gold': 10,
        'Silver': 4,
        'Bronze': 3,
        'Total': 17,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Defending',
        'Secondary': 'Defending',
        'Badge1': 'Defensive Stopper (HoF)',
        'Badge2': 'Pick Pocket (HoF)',
        'Badge3': 'Pick Dodger (HoF)',
        'Badge4': 'Charge Card (HoF)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 4,
        'Gold': 5,
        'Silver': 2,
        'Bronze': 5,
        'Total': 16,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Defending',
        'Secondary': 'Rebounding',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Pick Dodger (Gold)',
        'Badge4': 'Charge Card (Gold)',
        'Badge5': 'Pick Pocket (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 2,
        'Total': 17,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SHOOTING GUARD',
        'Primary': 'Defending',
        'Secondary': 'PostScoring',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Charge Card (Gold)',
        'Badge4': 'Pick Pocket (Gold)',
        'Badge5': 'Pick Dodger (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 2,
        'Total': 17,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Dimer (HoF)',
        'Badge2': 'Pick & Roll Maestro (HoF)',
        'Badge3': 'Lob City Passer (HoF)',
        'Badge4': 'Break Starter (HoF)',
        'Badge5': 'Flashy Passer (HoF)',
        'Ameythst': 5,
        'Gold': 5,
        'Silver': 3,
        'Bronze': 7,
        'Total': 20,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Shot Creating',
        'Badge1': 'Dimer (Gold)',
        'Badge2': 'Lob City Passer (Gold)',
        'Badge3': 'Pick & Roll Maestro (Gold)',
        'Badge4': 'Break Starter (Gold)',
        'Badge5': 'Flashy Passer (Gold)',
        'Ameythst': 0,
        'Gold': 11,
        'Silver': 4,
        'Bronze': 6,
        'Total': 21,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Lob City Passer (Gold)',
        'Badge2': 'Flashy Passer (Gold)',
        'Badge3': 'Dimer (Gold)',
        'Badge4': 'Pick & Roll Maestro (Gold)',
        'Badge5': 'Break Starter (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 9,
        'Bronze': 5,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Lob City Passer (Gold)',
        'Badge2': 'One Man Fast Break (Gold)',
        'Badge3': 'Dimer (Gold)',
        'Badge4': 'Pick & Roll Maestro (Gold)',
        'Badge5': 'Break Starter (Gold)',
        'Ameythst': 0,
        'Gold': 10,
        'Silver': 5,
        'Bronze': 8,
        'Total': 23,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Defending',
        'Badge1': 'Dimer (Gold)',
        'Badge2': 'Pick & Roll Maestro (Gold)',
        'Badge3': 'Lob City Passer (Gold)',
        'Badge4': 'Break Starter (Gold)',
        'Badge5': 'Flashy Passer (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 8,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'Rebounding',
        'Badge1': 'Break Starter (HoF)',
        'Badge2': 'Lob City Passer (Gold)',
        'Badge3': 'Dimer (Gold)',
        'Badge4': 'Pick & Roll Maestro (Gold)',
        'Badge5': 'Flashy Passer (Gold)',
        'Ameythst': 1,
        'Gold': 8,
        'Silver': 6,
        'Bronze': 7,
        'Total': 22,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Passing & Ballhandling',
        'Secondary': 'PostScoring',
        'Badge1': 'Lob City Passer (Gold)',
        'Badge2': 'Dimer (Gold)',
        'Badge3': 'Pick & Roll Maestro (Gold)',
        'Badge4': 'Break Starter (Gold)',
        'Badge5': 'Flashy Passer (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 9,
        'Bronze': 6,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Tireless Scorer (HoF)',
        'Badge2': 'Difficult Shots (HoF)',
        'Badge3': 'Mid Range Deadeye (Gold)',
        'Badge4': 'Tear Dropper (Gold)',
        'Badge5': 'One Man Fast Break (Silver)',
        'Ameythst': 2,
        'Gold': 5,
        'Silver': 9,
        'Bronze': 8,
        'Total': 24,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Shot Creating',
        'Badge1': 'Mid Range Deadeye (HoF)',
        'Badge2': 'Tear Dropper (HoF)',
        'Badge3': 'Tireless Scorer (HoF)',
        'Badge4': 'Difficult Shots (HoF)',
        'Badge5': 'Relentless Finisher (Silver)',
        'Ameythst': 4,
        'Gold': 3,
        'Silver': 3,
        'Bronze': 12,
        'Total': 22,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Shot Creating',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Tireless Scorer (HoF)',
        'Badge2': 'Difficult Shots (HoF)',
        'Badge3': 'Mid Range Deadeye (HoF)',
        'Badge4': 'Tear Dropper (Gold)',
        'Badge5': 'Corner Specialist (Silver)',
        'Ameythst': 3,
        'Gold': 4,
        'Silver': 6,
        'Bronze': 11,
        'Total': 24,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Tear Dropper (HoF)',
        'Badge2': 'Tireless Scorer (Gold)',
        'Badge3': 'Mid Range Deadeye (Gold)',
        'Badge4': 'Difficult Shots (Gold)',
        'Badge5': 'Relentless Finisher (Gold)',
        'Ameythst': 1,
        'Gold': 8,
        'Silver': 4,
        'Bronze': 10,
        'Total': 23,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Defending',
        'Badge1': 'Mid Range Deadeye (Gold)',
        'Badge2': 'Tear Dropper (Gold)',
        'Badge3': 'Tireless Scorer (Gold)',
        'Badge4': 'Difficult Shots (Gold)',
        'Badge5': 'Defensive Stopper (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 6,
        'Bronze': 13,
        'Total': 26,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Shot Creating',
        'Secondary': 'Rebounding',
        'Badge1': 'Mid Range Deadeye (Gold)',
        'Badge2': 'Tear Dropper (Gold)',
        'Badge3': 'Tireless Scorer (Gold)',
        'Badge4': 'Difficult Shots (Gold)',
        'Badge5': 'One Man Fast Break (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 8,
        'Bronze': 12,
        'Total': 27,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Shot Creating',
        'Secondary': 'PostScoring',
        'Badge1': 'Tear Dropper (Gold)',
        'Badge2': 'Tireless Scorer (Gold)',
        'Badge3': 'Mid Range Deadeye (Gold)',
        'Badge4': 'Difficult Shots (Gold)',
        'Badge5': 'Up & Under Specialist (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 4,
        'Bronze': 10,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Corner Specialist (Gold)',
        'Badge2': 'Catch & Shoot (Gold)',
        'Badge3': 'Deep Range Deadeye (Gold)',
        'Badge4': 'Limitless Range (Gold)',
        'Badge5': 'Pick & Popper (Gold)',
        'Ameythst': 0,
        'Gold': 9,
        'Silver': 7,
        'Bronze': 7,
        'Total': 23,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Shot Creating',
        'Badge1': 'Corner Specialist (Gold)',
        'Badge2': 'Catch & Shoot (Gold)',
        'Badge3': 'Pick & Popper (Gold)',
        'Badge4': 'Mid Range Deadeye (Gold)',
        'Badge5': 'Deep Range Deadeye (Gold)',
        'Ameythst': 0,
        'Gold': 9,
        'Silver': 4,
        'Bronze': 8,
        'Total': 21,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Catch & Shoot (HoF)',
        'Badge2': 'Deep Range Deadeye (HoF)',
        'Badge3': 'Limitless Range (HoF)',
        'Badge4': 'Corner Specialist (HoF)',
        'Badge5': 'Pick & Popper (Gold)',
        'Ameythst': 4,
        'Gold': 5,
        'Silver': 2,
        'Bronze': 6,
        'Total': 17,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Pick & Popper (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 9,
        'Bronze': 6,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Defending',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Pick & Popper (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 9,
        'Total': 24,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Rebounding',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Pick & Popper (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 8,
        'Bronze': 8,
        'Total': 24,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'PostScoring',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Deep Range Deadeye (Gold)',
        'Badge3': 'Limitless Range (Gold)',
        'Badge4': 'Corner Specialist (Gold)',
        'Badge5': 'Pick & Popper (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 6,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'One Man Fast Break (HoF)',
        'Badge2': 'Relentless Finisher (Gold)',
        'Badge3': 'Posterizer (Gold)',
        'Badge4': 'Lob City Finisher (Gold)',
        'Badge5': 'Acrobat (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 9,
        'Bronze': 7,
        'Total': 24,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Shot Creating',
        'Badge1': 'Relentless Finisher (HoF)',
        'Badge2': 'One Man Fastbreak (HoF)',
        'Badge3': 'Lob City Passer (Gold)',
        'Badge4': 'Posterizer (Gold)',
        'Badge5': 'Acrobat (Gold)',
        'Ameythst': 2,
        'Gold': 7,
        'Silver': 6,
        'Bronze': 7,
        'Total': 22,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Posterizer (Gold)',
        'Badge2': 'Relentless Finisher (Gold)',
        'Badge3': 'One Man Fast Break (Gold',
        'Badge4': 'Lob City Finisher (Gold)',
        'Badge5': 'Acrobat (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 10,
        'Total': 25,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Posterizer (HoF)',
        'Badge2': 'Relentless Finisher (HoF)',
        'Badge3': 'One Man Fastbreak (HoF)',
        'Badge4': 'Lob City Finisher (HoF)',
        'Badge5': 'Acrobat (Gold)',
        'Ameythst': 4,
        'Gold': 5,
        'Silver': 3,
        'Bronze': 7,
        'Total': 19,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Defending',
        'Badge1': 'Posterizer (HoF)',
        'Badge2': 'Lob City Finisher (HoF)',
        'Badge3': 'One Man Fast Break (Gold',
        'Badge4': 'Relentless Finisher (Gold)',
        'Badge5': 'Acrobat (Gold)',
        'Ameythst': 2,
        'Gold': 8,
        'Silver': 4,
        'Bronze': 6,
        'Total': 20,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Rebounding',
        'Badge1': 'Lob City Finisher (HoF)',
        'Badge2': 'Posterizer (HoF)',
        'Badge3': 'One Man Fast Break (HoF)',
        'Badge4': 'Relentless Finisher (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 3,
        'Gold': 6,
        'Silver': 6,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'PostScoring',
        'Badge1': 'Relentless Finisher (HoF)',
        'Badge2': 'Posterizer (Gold)',
        'Badge3': 'Lob City Finisher (Gold)',
        'Badge4': 'One Man Fast Break (Gold)',
        'Badge5': 'Acrobat (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 8,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Defending',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Charge Card (Gold)',
        'Badge3': 'Pick Pocket (Gold)',
        'Badge4': 'Chase Down Artist (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 11,
        'Bronze': 7,
        'Total': 26,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Defending',
        'Secondary': 'Shot Creating',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Chase Down Artist (Gold)',
        'Badge3': 'Charge Card (Gold)',
        'Badge4': 'Pick Pocket (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 9,
        'Bronze': 7,
        'Total': 24,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Defending',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Charge Card (Gold)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Pick Pocket (Gold)',
        'Badge4': 'Chase Down Artist (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 9,
        'Bronze': 9,
        'Total': 26,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Defending',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Chase Down Artist (HoF)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Charge Card (Gold)',
        'Badge4': 'Pick Pocket (Gold)',
        'Badge5': 'Posterizer (Gold)',
        'Ameythst': 1,
        'Gold': 9,
        'Silver': 7,
        'Bronze': 3,
        'Total': 20,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Defending',
        'Secondary': 'Defending',
        'Badge1': 'Defensive Stopper (HoF)',
        'Badge2': 'Pick Pocket (HoF)',
        'Badge3': 'Chase Down Artist (HoF)',
        'Badge4': 'Charge Card (HoF)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 4,
        'Gold': 5,
        'Silver': 4,
        'Bronze': 5,
        'Total': 18,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Defending',
        'Secondary': 'Rebounding',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Chase Down Artist (Gold)',
        'Badge3': 'Defensive Stopper (Gold)',
        'Badge4': 'Charge Card (Gold)',
        'Badge5': 'Pick Pocket (Gold)',
        'Ameythst': 1,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 2,
        'Total': 18,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Defending',
        'Secondary': 'PostScoring',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Charge Card (Gold)',
        'Badge4': 'Pick Pocket (Gold)',
        'Badge5': 'Chase Down Artist (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 8,
        'Bronze': 6,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Break Starter (HoF)',
        'Badge2': 'Hustle Rebounder (Gold)',
        'Badge3': 'Brick Wall (Gold)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 10,
        'Total': 25,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'Shot Creating',
        'Badge1': 'Hustle Rebounder (Gold)',
        'Badge2': 'Brick Wall (Gold)',
        'Badge3': 'Break Starter (Gold)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 4,
        'Bronze': 10,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Rebounding',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Hustle Rebounder (Gold)',
        'Badge2': 'Brick Wall (Gold)',
        'Badge3': 'Break Starter (Gold)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 6,
        'Bronze': 11,
        'Total': 25,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Putback King (HoF)',
        'Badge2': 'Hustle Rebounder (Gold)',
        'Badge3': 'Lob City Finisher (Gold)',
        'Badge4': 'Brick Wall (Gold)',
        'Badge5': 'Break Starter (Gold)',
        'Ameythst': 1,
        'Gold': 10,
        'Silver': 3,
        'Bronze': 6,
        'Total': 20,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'Defending',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Putback King (HoF)',
        'Badge3': 'Hustle Rebounder (Gold)',
        'Badge4': 'Brick Wall (Gold)',
        'Badge5': 'Break Starter (Gold)',
        'Ameythst': 2,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 2,
        'Total': 18,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'Rebounding',
        'Badge1': 'Hustle Rebounder (HoF)',
        'Badge2': 'Brick Wall (HoF)',
        'Badge3': 'Break Starter (HoF)',
        'Badge4': 'Bruiser (HoF)',
        'Badge5': 'Putback King (HoF)',
        'Ameythst': 5,
        'Gold': 4,
        'Silver': 2,
        'Bronze': 8,
        'Total': 19,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'PostScoring',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Brick Wall (HoF)',
        'Badge3': 'Hustle Rebounder (Gold)',
        'Badge4': 'Putback King (Gold)',
        'Badge5': 'Break Starter (Gold)',
        'Ameythst': 2,
        'Gold': 6,
        'Silver': 5,
        'Bronze': 9,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Post Spin Technician (Gold)',
        'Badge2': 'Drop-Stepper (Gold)',
        'Badge3': 'Bruiser (Gold)',
        'Badge4': 'Up & Under Specialist (Gold)',
        'Badge5': 'Relentless Finisher (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 13,
        'Total': 27,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'Shot Creating',
        'Badge1': 'Up & Under Specialist (HoF)',
        'Badge2': 'Post Spin Technician (Gold)',
        'Badge3': 'Drop-Stepper (Gold)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Relentless Finisher (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 5,
        'Bronze': 10,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'PostScoring',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Up & Under Specialist (Gold)',
        'Badge2': 'Post Spin Technician (Gold)',
        'Badge3': 'Drop-Stepper (Gold)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Relentless Finisher (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 8,
        'Bronze': 11,
        'Total': 26,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Post Spin Technician (Gold)',
        'Badge2': 'Relentless Finisher (Gold)',
        'Badge3': 'Drop-Stepper (Gold)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Up & Under Specialist (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 7,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'Defending',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Post Spin Technician (Gold)',
        'Badge3': 'Drop-Stepper (Gold)',
        'Badge4': 'Up & Under Specialist (Gold)',
        'Badge5': 'Defensive Stopper (Silver)',
        'Ameythst': 1,
        'Gold': 6,
        'Silver': 6,
        'Bronze': 10,
        'Total': 23,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'Rebounding',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Post Spin Technician (Gold)',
        'Badge3': 'Drop-Stepper (Gold)',
        'Badge4': 'Up & Under Specialist (Gold)',
        'Badge5': 'Brick Wall (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 4,
        'Bronze': 11,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'SMALL FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'PostScoring',
        'Badge1': 'Post Spin Technician (HoF)',
        'Badge2': 'Drop-Stepper (HoF)',
        'Badge3': 'Bruiser (HoF)',
        'Badge4': 'Up & Under Specialist (HoF)',
        'Badge5': 'Relentless Finisher (Gold)',
        'Ameythst': 4,
        'Gold': 4,
        'Silver': 1,
        'Bronze': 15,
        'Total': 24,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Corner Specialist (Gold)',
        'Badge2': 'Catch & Shoot (Gold)',
        'Badge3': 'Pick & Popper (Gold)',
        'Badge4': 'Deep Range Deadeye (Gold)',
        'Badge5': 'Limitless Range (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 8,
        'Bronze': 7,
        'Total': 22,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Shot Creating',
        'Badge1': 'Corner Specialist (Gold)',
        'Badge2': 'Catch & Shoot (Gold)',
        'Badge3': 'Pick & Popper (Gold)',
        'Badge4': 'Mid Range Deadeye (Gold)',
        'Badge5': 'Deep Range Deadeye (Gold)',
        'Ameythst': 0,
        'Gold': 9,
        'Silver': 4,
        'Bronze': 8,
        'Total': 21,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Catch & Shoot (HoF)',
        'Badge2': 'Corner Specialist (HoF)',
        'Badge3': 'Pick & Popper (HoF)',
        'Badge4': 'Deep Range Deadeye (Gold)',
        'Badge5': 'Limitless Range (Gold)',
        'Ameythst': 3,
        'Gold': 5,
        'Silver': 4,
        'Bronze': 4,
        'Total': 16,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Corner Specialist (Gold)',
        'Badge3': 'Pick & Popper (Gold)',
        'Badge4': 'Deep Range Deadeye (Gold)',
        'Badge5': 'Pick & Roller (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 8,
        'Bronze': 11,
        'Total': 26,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Defending',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Corner Specialist (Gold)',
        'Badge3': 'Pick & Popper (Gold)',
        'Badge4': 'Deep Range Deadeye (Gold)',
        'Badge5': 'Limitless Range (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 8,
        'Bronze': 8,
        'Total': 23,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'Rebounding',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Corner Specialist (Gold)',
        'Badge3': 'Pick & Popper (Gold)',
        'Badge4': 'Deep Range Deadeye (Gold)',
        'Badge5': 'Limitless Range (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 10,
        'Bronze': 5,
        'Total': 22,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': '3 Point Shooting',
        'Secondary': 'PostScoring',
        'Badge1': 'Pick & Popper (Gold)',
        'Badge2': 'Catch & Shoot (Gold)',
        'Badge3': 'Corner Specialist (Gold)',
        'Badge4': 'Up & Under Specialist (Gold)',
        'Badge5': 'Deep Range Deadeye (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 8,
        'Bronze': 3,
        'Total': 19,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Relentless Finisher (Gold)',
        'Badge2': 'Posterizer (Gold)',
        'Badge3': 'Pick & Roller (Gold)',
        'Badge4': 'Lob City Finisher (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 8,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Shot Creating',
        'Badge1': 'Relentless Finisher (HoF)',
        'Badge2': 'Pick & Roller (HoF)',
        'Badge3': 'Lob City Finisher (HoF)',
        'Badge4': 'Posterizer (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 3,
        'Gold': 5,
        'Silver': 7,
        'Bronze': 8,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Pick & Roller (Gold)',
        'Badge2': 'Posterizer (Gold)',
        'Badge3': 'Relentless Finisher (Gold)',
        'Badge4': 'Lob City Finisher (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 5,
        'Bronze': 14,
        'Total': 27,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Posterizer (HoF)',
        'Badge2': 'Relentless Finisher (HoF)',
        'Badge3': 'Pick & Roller (HoF)',
        'Badge4': 'Lob City Finisher (HoF)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 4,
        'Gold': 4,
        'Silver': 6,
        'Bronze': 7,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Defending',
        'Badge1': 'Lob City Finisher (HoF)',
        'Badge2': 'Posterizer (HoF)',
        'Badge3': 'Pick & Roller (Gold)',
        'Badge4': 'Putback King (Gold)',
        'Badge5': 'Relentless Finisher (Gold)',
        'Ameythst': 2,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 4,
        'Total': 20,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Rebounding',
        'Badge1': 'Lob City Finisher (HoF)',
        'Badge2': 'Posterizer (HoF)',
        'Badge3': 'Pick & Roller (HoF)',
        'Badge4': 'Putback King (HoF)',
        'Badge5': 'Relentless Finisher (Gold)',
        'Ameythst': 4,
        'Gold': 5,
        'Silver': 6,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Driving & Finishing',
        'Secondary': 'PostScoring',
        'Badge1': 'Relentless Finisher (HoF)',
        'Badge2': 'Pick & Roller (HoF)',
        'Badge3': 'Posterizer (Gold)',
        'Badge4': 'Lob City Finisher (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 2,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 6,
        'Total': 22,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Defending',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Charge Card (Gold)',
        'Badge3': 'Rim Protector (Gold)',
        'Badge4': 'Chase Down Artist (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 8,
        'Bronze': 7,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Defending',
        'Secondary': 'Shot Creating',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Rim Protector (Gold)',
        'Badge3': 'Chase Down Artist (Gold)',
        'Badge4': 'Charge Card (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 0,
        'Gold': 9,
        'Silver': 6,
        'Bronze': 10,
        'Total': 25,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Defending',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Charge Card (Gold)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Rim Protector (Gold)',
        'Badge4': 'Chase Down Artist (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 9,
        'Total': 24,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Defending',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Chase Down Artist (HoF)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Rim Protector (Gold)',
        'Badge4': 'Charge Card (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 1,
        'Gold': 10,
        'Silver': 4,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Defending',
        'Secondary': 'Defending',
        'Badge1': 'Defensive Stopper (HoF)',
        'Badge2': 'Rim Protector (HoF)',
        'Badge3': 'Chase Down Artist (HoF)',
        'Badge4': 'Charge Card (HoF)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 4,
        'Gold': 5,
        'Silver': 4,
        'Bronze': 4,
        'Total': 17,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Defending',
        'Secondary': 'Rebounding',
        'Badge1': 'Rim Protector (HoF)',
        'Badge2': 'Bruiser (HoF)',
        'Badge3': 'Chase Down Artist (Gold)',
        'Badge4': 'Putback King (Gold)',
        'Badge5': 'Defensive Stopper (Gold)',
        'Ameythst': 2,
        'Gold': 8,
        'Silver': 4,
        'Bronze': 2,
        'Total': 16,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Defending',
        'Secondary': 'PostScoring',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Rim Protector (Gold)',
        'Badge4': 'Charge Card (Gold)',
        'Badge5': 'Chase Down Artist (Gold)',
        'Ameythst': 1,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 3,
        'Total': 19,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Break Starter (HoF)',
        'Badge2': 'Brick Wall (Gold)',
        'Badge3': 'Hustle Rebounder (Gold)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 7,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'Shot Creating',
        'Badge1': 'Hustle Rebounder (Gold)',
        'Badge2': 'Putback King (Gold)',
        'Badge3': 'Brick Wall (Gold)',
        'Badge4': 'Break Starter (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 4,
        'Bronze': 10,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Rebounding',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Bruiser (Gold)',
        'Badge2': 'Brick Wall (Gold)',
        'Badge3': 'Hustle Rebounder (Gold)',
        'Badge4': 'Break Starter (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 9,
        'Total': 24,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Putback King (HoF)',
        'Badge2': 'Hustle Rebounder (HoF)',
        'Badge3': 'Brick Wall (Gold)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Lob City Finisher (Gold)',
        'Ameythst': 2,
        'Gold': 9,
        'Silver': 3,
        'Bronze': 6,
        'Total': 20,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'Defending',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Putback King (HoF)',
        'Badge3': 'Brick Wall (HoF)',
        'Badge4': 'Hustle Rebounder (Gold)',
        'Badge5': 'Break Starter (Gold)',
        'Ameythst': 3,
        'Gold': 7,
        'Silver': 5,
        'Bronze': 2,
        'Total': 17,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'Rebounding',
        'Badge1': 'Hustle Rebounder (HoF)',
        'Badge2': 'Brick Wall (HoF)',
        'Badge3': 'Break Starter (HoF)',
        'Badge4': 'Bruiser (HoF)',
        'Badge5': 'Putback King (HoF)',
        'Ameythst': 5,
        'Gold': 4,
        'Silver': 3,
        'Bronze': 6,
        'Total': 18,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'Rebounding',
        'Secondary': 'PostScoring',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Brick Wall (HoF)',
        'Badge3': 'Putback King (HoF)',
        'Badge4': 'Hustle Rebounder (Gold)',
        'Badge5': 'Break Starter (Gold)',
        'Ameythst': 3,
        'Gold': 5,
        'Silver': 7,
        'Bronze': 4,
        'Total': 19,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Post Spin Technician (HoF)',
        'Badge2': 'Drop-Stepper (HoF)',
        'Badge3': 'Bruiser (Gold)',
        'Badge4': 'Up & Under Specialist (Gold)',
        'Badge5': 'Brick Wall (Gold)',
        'Ameythst': 2,
        'Gold': 6,
        'Silver': 6,
        'Bronze': 9,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'Shot Creating',
        'Badge1': 'Up & Under Specialist (HoF)',
        'Badge2': 'Post Spin Technician (HoF)',
        'Badge3': 'Drop-Stepper (HoF)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Brick Wall (Gold)',
        'Ameythst': 3,
        'Gold': 5,
        'Silver': 4,
        'Bronze': 8,
        'Total': 20,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'PostScoring',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Up & Under Specialist (HoF)',
        'Badge2': 'Bruiser (Gold)',
        'Badge3': 'Post Spin Technician (Gold)',
        'Badge4': 'Drop-Stepper (Gold)',
        'Badge5': 'Brick Wall (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 5,
        'Bronze': 12,
        'Total': 25,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Post Spin Technician (HoF)',
        'Badge2': 'Drop-Stepper (Gold)',
        'Badge3': 'Bruiser (Gold)',
        'Badge4': 'Relentless Finisher (Gold)',
        'Badge5': 'Up & Under Specialist (Gold)',
        'Ameythst': 1,
        'Gold': 9,
        'Silver': 4,
        'Bronze': 8,
        'Total': 22,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'Defending',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Post Spin Technician (Gold)',
        'Badge3': 'Drop-Stepper (Gold)',
        'Badge4': 'Up & Under Specialist (Gold)',
        'Badge5': 'Brick Wall (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 9,
        'Bronze': 3,
        'Total': 20,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'Rebounding',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Brick Wall (HoF)',
        'Badge3': 'Up & Under Specialist (Gold)',
        'Badge4': 'Post Spin Technician (Gold)',
        'Badge5': 'Drop-Stepper (Gold)',
        'Ameythst': 2,
        'Gold': 7,
        'Silver': 6,
        'Bronze': 4,
        'Total': 19,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'POWER FORWARD',
        'Primary': 'PostScoring',
        'Secondary': 'PostScoring',
        'Badge1': 'Post Spin Technician (HoF)',
        'Badge2': 'Drop-Stepper (HoF)',
        'Badge3': 'Bruiser (HoF)',
        'Badge4': 'Up & Under Specialist (HoF)',
        'Badge5': 'Brick Wall (Gold)',
        'Ameythst': 4,
        'Gold': 5,
        'Silver': 2,
        'Bronze': 10,
        'Total': 21,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': '3 Point Shooting',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Corner Specialist (Gold)',
        'Badge2': 'Catch & Shoot (Gold)',
        'Badge3': 'Pick & Popper (Gold)',
        'Badge4': 'Deep Range Deadeye (Gold)',
        'Badge5': 'Limitless Range (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 9,
        'Bronze': 6,
        'Total': 22,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'CENTER',
        'Primary': '3 Point Shooting',
        'Secondary': 'Shot Creating',
        'Badge1': 'Corner Specialist (Gold)',
        'Badge2': 'Catch & Shoot (Gold)',
        'Badge3': 'Pick & Popper (Gold)',
        'Badge4': 'Mid Range Deadeye (Gold)',
        'Badge5': 'Limitless Range (Gold)',
        'Ameythst': 0,
        'Gold': 9,
        'Silver': 4,
        'Bronze': 8,
        'Total': 21,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': '3 Point Shooting',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Catch & Shoot (HoF)',
        'Badge2': 'Corner Specialist (HoF)',
        'Badge3': 'Pick & Popper (HoF)',
        'Badge4': 'Deep Range Deadeye (Gold)',
        'Badge5': 'Limitless Range (Gold)',
        'Ameythst': 3,
        'Gold': 5,
        'Silver': 5,
        'Bronze': 3,
        'Total': 16,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': '3 Point Shooting',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Corner Specialist (Gold)',
        'Badge3': 'Pick & Popper (Gold)',
        'Badge4': 'Pick & Roller (Gold)',
        'Badge5': 'Deep Range Deadeye (Gold)',
        'Ameythst': 0,
        'Gold': 6,
        'Silver': 7,
        'Bronze': 11,
        'Total': 24,
        'Amethyst and Gold': 6,
    },
    {
        'Position': 'CENTER',
        'Primary': '3 Point Shooting',
        'Secondary': 'Defending',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Corner Specialist (Gold)',
        'Badge3': 'Pick & Popper (Gold)',
        'Badge4': 'Deep Range Deadeye (Gold)',
        'Badge5': 'Limitless Range (Silver)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 9,
        'Bronze': 7,
        'Total': 23,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'CENTER',
        'Primary': '3 Point Shooting',
        'Secondary': 'Rebounding',
        'Badge1': 'Catch & Shoot (Gold)',
        'Badge2': 'Corner Specialist (Gold)',
        'Badge3': 'Pick & Popper (Gold)',
        'Badge4': 'Limitless Range (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 7,
        'Silver': 10,
        'Bronze': 5,
        'Total': 22,
        'Amethyst and Gold': 7,
    },
    {
        'Position': 'CENTER',
        'Primary': '3 Point Shooting',
        'Secondary': 'PostScoring',
        'Badge1': 'Pick & Popper (Gold)',
        'Badge2': 'Catch & Shoot (Gold)',
        'Badge3': 'Corner Specialist (Gold)',
        'Badge4': 'Up & Under Specialist (Gold)',
        'Badge5': 'Deep Range Deadeye (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 9,
        'Bronze': 4,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Relentless Finisher (Gold)',
        'Badge2': 'Posterizer (Gold)',
        'Badge3': 'Pick & Roller (Gold)',
        'Badge4': 'Lob City Finisher (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 7,
        'Bronze': 8,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Shot Creating',
        'Badge1': 'Relentless Finisher (HoF)',
        'Badge2': 'Pick & Roller (HoF)',
        'Badge3': 'Lob City Finisher (HoF)',
        'Badge4': 'Posterizer (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 3,
        'Gold': 5,
        'Silver': 7,
        'Bronze': 8,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Driving & Finishing',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Pick & Roller (HoF)',
        'Badge2': 'Posterizer (Gold)',
        'Badge3': 'Relentless Finisher (Gold)',
        'Badge4': 'Lob City Finisher (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 4,
        'Bronze': 15,
        'Total': 27,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Posterizer (HoF)',
        'Badge2': 'Relentless Finisher (HoF)',
        'Badge3': 'Pick & Roller (HoF)',
        'Badge4': 'Lob City Finisher (HoF)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 4,
        'Gold': 4,
        'Silver': 6,
        'Bronze': 7,
        'Total': 21,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Defending',
        'Badge1': 'Lob City Finisher (HoF)',
        'Badge2': 'Posterizer (HoF)',
        'Badge3': 'Pick & Roller (Gold)',
        'Badge4': 'Putback King (Gold)',
        'Badge5': 'Relentless Finisher (Gold)',
        'Ameythst': 2,
        'Gold': 7,
        'Silver': 6,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Driving & Finishing',
        'Secondary': 'Rebounding',
        'Badge1': 'Lob City Finisher (HoF)',
        'Badge2': 'Posterizer (HoF)',
        'Badge3': 'Pick & Roller (HoF)',
        'Badge4': 'Putback King (HoF)',
        'Badge5': 'Relentless Finisher (Gold)',
        'Ameythst': 4,
        'Gold': 5,
        'Silver': 5,
        'Bronze': 6,
        'Total': 20,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Driving & Finishing',
        'Secondary': 'PostScoring',
        'Badge1': 'Relentless Finisher (HoF)',
        'Badge2': 'Pick & Roller (HoF)',
        'Badge3': 'Posterizer (Gold)',
        'Badge4': 'Lob City Finisher (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 2,
        'Gold': 7,
        'Silver': 6,
        'Bronze': 7,
        'Total': 22,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Defending',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Charge Card (Gold)',
        'Badge3': 'Rim Protector (Gold)',
        'Badge4': 'Chase Down Artist (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 8,
        'Bronze': 6,
        'Total': 22,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Defending',
        'Secondary': 'Shot Creating',
        'Badge1': 'Defensive Stopper (Gold)',
        'Badge2': 'Rim Protector (Gold)',
        'Badge3': 'Bruiser (Gold)',
        'Badge4': 'Charge Card (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 0,
        'Gold': 9,
        'Silver': 5,
        'Bronze': 9,
        'Total': 23,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Defending',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Charge Card (Gold)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Rim Protector (Gold)',
        'Badge4': 'Chase Down Artist (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 8,
        'Silver': 8,
        'Bronze': 8,
        'Total': 24,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Defending',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Chase Down Artist (HoF)',
        'Badge2': 'Defensive Stopper (Gold)',
        'Badge3': 'Rim Protector (Gold)',
        'Badge4': 'Charge Card (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 1,
        'Gold': 10,
        'Silver': 4,
        'Bronze': 5,
        'Total': 20,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Defending',
        'Secondary': 'Defending',
        'Badge1': 'Defensive Stopper (HoF)',
        'Badge2': 'Rim Protector (HoF)',
        'Badge3': 'Chase Down Artist (HoF)',
        'Badge4': 'Charge Card (HoF)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 4,
        'Gold': 5,
        'Silver': 4,
        'Bronze': 3,
        'Total': 16,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Defending',
        'Secondary': 'Rebounding',
        'Badge1': 'Rim Protector (HoF)',
        'Badge2': 'Bruiser (HoF)',
        'Badge3': 'Chase Down Artist (Gold)',
        'Badge4': 'Putback King (Gold)',
        'Badge5': 'Defensive Stopper (Gold)',
        'Ameythst': 2,
        'Gold': 9,
        'Silver': 4,
        'Bronze': 2,
        'Total': 17,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Defending',
        'Secondary': 'PostScoring',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Rim Protector (HoF)',
        'Badge3': 'Defensive Stopper (Gold)',
        'Badge4': 'Charge Card (Gold)',
        'Badge5': 'Chase Down Artist (Gold)',
        'Ameythst': 2,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 3,
        'Total': 19,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Rebounding',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Break Starter (HoF)',
        'Badge2': 'Brick Wall (Gold)',
        'Badge3': 'Hustle Rebounder (Gold)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 8,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Rebounding',
        'Secondary': 'Shot Creating',
        'Badge1': 'Hustle Rebounder (Gold)',
        'Badge2': 'Putback King (Gold)',
        'Badge3': 'Brick Wall (Gold)',
        'Badge4': 'Break Starter (Gold)',
        'Badge5': 'Bruiser (Gold)',
        'Ameythst': 0,
        'Gold': 9,
        'Silver': 4,
        'Bronze': 10,
        'Total': 23,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Rebounding',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Bruiser (Gold)',
        'Badge2': 'Brick Wall (Gold)',
        'Badge3': 'Hustle Rebounder (Gold)',
        'Badge4': 'Break Starter (Gold)',
        'Badge5': 'Putback King (Gold)',
        'Ameythst': 0,
        'Gold': 9,
        'Silver': 7,
        'Bronze': 9,
        'Total': 25,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Rebounding',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Putback King (HoF)',
        'Badge2': 'Hustle Rebounder (HoF)',
        'Badge3': 'Brick Wall (Gold)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Lob City Finisher (Gold)',
        'Ameythst': 2,
        'Gold': 9,
        'Silver': 3,
        'Bronze': 6,
        'Total': 20,
        'Amethyst and Gold': 11,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Rebounding',
        'Secondary': 'Defending',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Putback King (HoF)',
        'Badge3': 'Brick Wall (HoF)',
        'Badge4': 'Hustle Rebounder (Gold)',
        'Badge5': 'Break Starter (Gold)',
        'Ameythst': 3,
        'Gold': 7,
        'Silver': 5,
        'Bronze': 2,
        'Total': 17,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Rebounding',
        'Secondary': 'Rebounding',
        'Badge1': 'Hustle Rebounder (HoF)',
        'Badge2': 'Brick Wall (HoF)',
        'Badge3': 'Break Starter (HoF)',
        'Badge4': 'Bruiser (HoF)',
        'Badge5': 'Putback King (HoF)',
        'Ameythst': 5,
        'Gold': 4,
        'Silver': 3,
        'Bronze': 6,
        'Total': 18,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'Rebounding',
        'Secondary': 'PostScoring',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Brick Wall (HoF)',
        'Badge3': 'Putback King (HoF)',
        'Badge4': 'Hustle Rebounder (Gold)',
        'Badge5': 'Break Starter (Gold)',
        'Ameythst': 3,
        'Gold': 5,
        'Silver': 7,
        'Bronze': 4,
        'Total': 19,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': 'PostScoring',
        'Secondary': 'Passing & Ballhandling',
        'Badge1': 'Post Spin Technician (HoF)',
        'Badge2': 'Drop-Stepper (HoF)',
        'Badge3': 'Up & Under Specialist (Gold)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Brick Wall (Gold)',
        'Ameythst': 2,
        'Gold': 6,
        'Silver': 6,
        'Bronze': 9,
        'Total': 23,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': 'PostScoring',
        'Secondary': 'Shot Creating',
        'Badge1': 'Up & Under Specialist (HoF)',
        'Badge2': 'Post Spin Technician (HoF)',
        'Badge3': 'Drop-Stepper (HoF)',
        'Badge4': 'Bruiser (Gold)',
        'Badge5': 'Brick Wall (Gold)',
        'Ameythst': 3,
        'Gold': 6,
        'Silver': 5,
        'Bronze': 7,
        'Total': 21,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'PostScoring',
        'Secondary': '3 Point Shooting',
        'Badge1': 'Up & Under Specialist (HoF)',
        'Badge2': 'Bruiser (Gold)',
        'Badge3': 'Post Spin Technician (Gold)',
        'Badge4': 'Drop-Stepper (Gold)',
        'Badge5': 'Brick Wall (Gold)',
        'Ameythst': 1,
        'Gold': 7,
        'Silver': 5,
        'Bronze': 12,
        'Total': 25,
        'Amethyst and Gold': 8,
    },
    {
        'Position': 'CENTER',
        'Primary': 'PostScoring',
        'Secondary': 'Driving & Finishing',
        'Badge1': 'Post Spin Technician (HoF)',
        'Badge2': 'Drop-Stepper (Gold)',
        'Badge3': 'Bruiser (Gold)',
        'Badge4': 'Relentless Finisher (Gold)',
        'Badge5': 'Up & Under Specialist (Gold)',
        'Ameythst': 1,
        'Gold': 9,
        'Silver': 5,
        'Bronze': 7,
        'Total': 22,
        'Amethyst and Gold': 10,
    },
    {
        'Position': 'CENTER',
        'Primary': 'PostScoring',
        'Secondary': 'Defending',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Post Spin Technician (Gold)',
        'Badge3': 'Drop-Stepper (Gold)',
        'Badge4': 'Up & Under Specialist (Gold)',
        'Badge5': 'Brick Wall (Gold)',
        'Ameythst': 1,
        'Gold': 8,
        'Silver': 8,
        'Bronze': 3,
        'Total': 20,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'PostScoring',
        'Secondary': 'Rebounding',
        'Badge1': 'Bruiser (HoF)',
        'Badge2': 'Brick Wall (HoF)',
        'Badge3': 'Up & Under Specialist (Gold)',
        'Badge4': 'Post Spin Technician (Gold)',
        'Badge5': 'Drop-Stepper (Gold)',
        'Ameythst': 2,
        'Gold': 7,
        'Silver': 7,
        'Bronze': 3,
        'Total': 19,
        'Amethyst and Gold': 9,
    },
    {
        'Position': 'CENTER',
        'Primary': 'PostScoring',
        'Secondary': 'PostScoring',
        'Badge1': 'Post Spin Technician (HoF)',
        'Badge2': 'Drop-Stepper (HoF)',
        'Badge3': 'Bruiser (HoF)',
        'Badge4': 'Up & Under Specialist (HoF)',
        'Badge5': 'Brick Wall (Gold)',
        'Ameythst': 4,
        'Gold': 5,
        'Silver': 3,
        'Bronze': 9,
        'Total': 21,
        'Amethyst and Gold': 9,
    },
]
