player_index = {
    'Giannis Antetokounmpo': {
        'Weight': 220,
        'Position': 'PF',
        'Height': 83,
        'attributes': {
            'ShotClose': 87,
            'OpenMid': 66,
            'ContestMid': 70,
            'OffDribbleMid': 65,
            'OpenThree': 77,
            'ContestedThree': 69,
            'OffDribbleThree': 65,
            'StandingLayup': 98,
            'DrivingLayup': 97,
            'StandingDunk': 50,
            'DrivingDunk': 90,
            'BallControl': 83,
            'PassingAccuracy': 81,
            'PostControl': 72,
            'PostHook': 69,
            'PostFadeaway': 69,
            'OffensiveRebound': 58,
            'DefensiveRebound': 86,
            'Boxout': 88,
            'PassPerception': 65,
            'Steal': 72,
            'Block': 88,
            'ShotContest': 95,
            'LateralQuickness': 90,
            'Speed': 91,
            'Acceleration': 88,
            'Vertical': 85,
            'Strength': 70
        }
    },
    'Stephen Curry': {
        'Weight': 190,
        'Position': 'PG',
        'Height': 75,
        'attributes': {
            'ShotClose': 92,
            'OpenMid': 93,
            'ContestMid': 98,
            'OffDribbleMid': 93,
            'OpenThree': 99,
            'ContestedThree': 99,
            'OffDribbleThree': 99,
            'StandingLayup': 97,
            'DrivingLayup': 97,
            'StandingDunk': 25,
            'DrivingDunk': 36,
            'BallControl': 94,
            'PassingAccuracy': 90,
            'PostControl': 32,
            'PostHook': 35,
            'PostFadeaway': 52,
            'OffensiveRebound': 38,
            'DefensiveRebound': 61,
            'Boxout': 64,
            'PassPerception': 85,
            'Steal': 78,
            'Block': 32,
            'ShotContest': 82,
            'LateralQuickness': 83,
            'Speed': 85,
            'Acceleration': 95,
            'Vertical': 73,
            'Strength': 48
        }
    },
    'Karl-Anthony Towns': {
        'Weight': 244,
        'Position': 'C',
        'Height': 82,
        'attributes': {
            'ShotClose': 87,
            'OpenMid': 66,
            'ContestMid': 70,
            'OffDribbleMid': 65,
            'OpenThree': 77,
            'ContestedThree': 69,
            'OffDribbleThree': 65,
            'StandingLayup': 98,
            'DrivingLayup': 97,
            'StandingDunk': 50,
            'DrivingDunk': 90,
            'BallControl': 83,
            'PassingAccuracy': 81,
            'PostControl': 72,
            'PostHook': 69,
            'PostFadeaway': 69,
            'OffensiveRebound': 58,
            'DefensiveRebound': 86,
            'Boxout': 88,
            'PassPerception': 65,
            'Steal': 72,
            'Block': 88,
            'ShotContest': 95,
            'LateralQuickness': 90,
            'Speed': 91,
            'Acceleration': 88,
            'Vertical': 85,
            'Strength': 70
        }
    },
}
